#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
  path: /
  controller: App\Controller\HomeController::home

# on utilise le TemplateController pour afficher une page statique 
cgv:
  path: /cgv
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: 'statique/cgv.html.twig'

contact:
  path: /contact
  controller : Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: 'statique/contact.html.twig'

devenirBlogueur:
  path: /devenirBlogueur
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: 'statique/devenirBlogueur.html.twig'  

joinTeam:
  path: /join-team
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: 'statique/joinTeam.html.twig'        
   
quiSommesNous:
  path: /qu-Sommes-Nous
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: 'statique/quiSommesNous.html.twig'

valeurs:
  path: /valeurs
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: 'statique/values.html.twig'